services:

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana
    ports:
      - "53000:3000"
    networks:
      - grafanet
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: grafana-db
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /opt/databases/prod/grafana/postgresql/data:/var/lib/postgresql/data
    networks:
      - grafanet
    restart: unless-stopped

networks:
  grafanet:
    driver: bridge

